### ISSUE TITLE
Pinging people interested in gist.io

### ISSUE THREAD

**Issue by x3ro** [x3ro/draft.sx#1]
Hey everyone :) I'm pinging you here because you've expressed interest in gist.io, which is currently not working and has only been sporadically maintained in the past. I've created this fork because I like the idea and wanted to keep it alive. I'd welcome contributions in form of code, but also in form of testing and using the site.

@dmd @aboutaaron @nodiscc @jdickey @MarkKettner @BukhariH @shapeshed @programble @antoinelyset @yunga @miniops @clrh @szexigexi @mikejholly @nwjlyons @dajare @gregory @xbelanch @almereyda @lolmaus

**Comment by x3ro** [comment]
Pinging some more people that seem to have problems with using gist.io - @code4wd @staeff :smile:

**Comment by staeff** [comment]
Hey @x3ro, your message slipped through until now. I am very interested in this and will try it out soon. Maybe I can contribute something :-)
Thanks for your initiative!
