### ISSUE TITLE
Can haz tables support? :)

### ISSUE THREAD

**Issue by awalGarg** [x3ro/draft.sx#10]
It doesn't seem that tables work. Example: https://draft.sx/d1c403c1ab902480c2bb
Works in gist: https://gist.github.com/awalGarg/d1c403c1ab902480c2bb
Markdown: https://gist.githubusercontent.com/awalGarg/d1c403c1ab902480c2bb/raw/75038d676f295122cc6293ebe379ace91aa57e84/tables.md

Would be really nice to see tables rendered as well :)

Thanks for the awesome service!

**Comment by x3ro** [comment]
Hey @awalGarg :smile: Thanks for the suggestion. I've enabled table support and pushed a new version!

**Comment by awalGarg** [comment]
Awesome, thanks a ton!
