### ISSUE TITLE
User Pages

### ISSUE THREAD

**Issue by nasser** [x3ro/draft.sx#12]
RoughDraft has a cool feature where it consolidates your Gists on a "user page", e.g. mine is http://nasser.roughdraft.io/. Maybe a route like `draft.sx/u/nasser` could work for draft?

**Comment by x3ro** [comment]
So this would only show documents that have already been viewed via draft.sx, and not those that are secret? @nasser Because showing all gists of the person doesn't seem like a good idea, same as showing secret gists in the list (imo).

**Comment by x3ro** [comment]
Closing due to lack of feedback ⏳
