### ISSUE TITLE
Emoji support!

### ISSUE THREAD

**Issue by lolmaus** [x3ro/draft.sx#13]
:tada: :confetti_ball: :dancers: :beers:

**Comment by x3ro** [comment]
👍 🍺 🎉

**Comment by lolmaus** [comment]
![image](https://cloud.githubusercontent.com/assets/200884/16570115/f5fe5d1e-4247-11e6-84a5-de27a1b6dfcb.png)

**Comment by x3ro** [comment]
Interesting :D Makes sense too, since it probably relies on emoji in the font, and does not replace it with images

**Comment by x3ro** [comment]
Now uses SVG emoji :)

**Comment by lolmaus** [comment]
Niiiice!

![image](https://cloud.githubusercontent.com/assets/200884/16570438/ad3ca666-424d-11e6-98c5-90dc083c3d20.png)

**Comment by lolmaus** [comment]
Please apply `vertical-align: middle` to emojis.
